import { model, Schema } from "mongoose";

const uniproProduct = new Schema({
  barcode: { type: String, required: true },
  barcode2: { type: String, default: "" },
  barcode3: { type: String, default: "" },
  barcodelist: { type: String, default: "" },
  code: { type: String, required: true },
  coeff2: { type: Number, default: 1 },
  coeff3: { type: Number, default: 1 },
  del: { type: Number, default: 0 },
  desc: { type: String, default: "" },
  dopprop1: { type: String, default: "" },
  dopprop2: { type: String, default: "" },
  dopprop3: { type: String, default: "" },
  dopprop4: { type: String, default: "" },
  dopprop5: { type: String, default: "" },
  group: { type: String, required: true },
  guid: { type: String, required: true },
  lid: { type: Number, required: true },
  lost: { type: Number, default: 0 },
  min: { type: Number, default: 0 },
  name: { type: String, required: true },
  namefull: { type: String, required: true },
  nom: { type: Number, default: 0 },
  outw: { type: Number, default: 0 },
  p1: { type: Number, required: true },
  p2: { type: Number, default: 0 },
  p3: { type: Number, default: 0 },
  p4: { type: Number, default: 0 },
  p5: { type: Number, default: 0 },
  p6: { type: Number, default: 0 },
  p7: { type: Number, default: 0 },
  p8: { type: Number, default: 0 },
  p9: { type: Number, default: 0 },
  p10: { type: Number, default: 0 },
  piece: { type: Number, default: 0 },
  pin: { type: Number, required: true },
  plu: { type: Number, default: 0 },
  qtty: { type: Number, required: true },
  scs: { type: Number, default: 0 },
  tare: { type: Number, default: 0 },
  type: { type: Number, default: 0 },
  uktzed: { type: String, default: "" },
  unit1: { type: String },
  unit2: { type: String },
  unit3: { type: String },
  vat: { type: Number, required: true },
  vendor: { type: String },
  visible: { type: Number, default: 1 },
});

const uniproProducts = model("unipro", uniproProduct);

export default uniproProducts;
